// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYw0zZiuqyhO0TyxLuqZDoR8mscMCoWpg',
    appId: '1:394386899283:web:a7cbd83fdd396f5db021a6',
    messagingSenderId: '394386899283',
    projectId: 'chatapp-df180',
    authDomain: 'chatapp-df180.firebaseapp.com',
    storageBucket: 'chatapp-df180.firebasestorage.app',
    measurementId: 'G-QNL30BNBT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCE1GnI4q_RemMTX0uuG8ScW-xZBs_hqk',
    appId: '1:394386899283:android:bc7b7bbca30b832ab021a6',
    messagingSenderId: '394386899283',
    projectId: 'chatapp-df180',
    storageBucket: 'chatapp-df180.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL7pCLAuDoOYynjJGi88mP2ZlMU8Mv-_4',
    appId: '1:394386899283:ios:6d1e02b647661381b021a6',
    messagingSenderId: '394386899283',
    projectId: 'chatapp-df180',
    storageBucket: 'chatapp-df180.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL7pCLAuDoOYynjJGi88mP2ZlMU8Mv-_4',
    appId: '1:394386899283:ios:6d1e02b647661381b021a6',
    messagingSenderId: '394386899283',
    projectId: 'chatapp-df180',
    storageBucket: 'chatapp-df180.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYw0zZiuqyhO0TyxLuqZDoR8mscMCoWpg',
    appId: '1:394386899283:web:3a31a97314e4f356b021a6',
    messagingSenderId: '394386899283',
    projectId: 'chatapp-df180',
    authDomain: 'chatapp-df180.firebaseapp.com',
    storageBucket: 'chatapp-df180.firebasestorage.app',
    measurementId: 'G-91MGN21VG5',
  );
}
